domain: example.com
email: mail@example.com

mode: dev            # dev | prod

server:
  user: root
  ip:   192.168.111.222
  path: /

nginx:
  http_port: 8080    # dev: чтобы не биться с локальным :80
  https_port: 8443   # dev: чтобы не биться с локальным :443
  certs_path: ./volumes/certs
  webroot_path: ./volumes/certbot-www

features:
  certbot_enabled: false   # dev=false, prod=true

services:
  router:
    container_name: router
  certbot:
    container_name: certbot
  frontend:
    container_name: frontend
  backend:
    container_name: backend

