version: "3.9"

services:
  router:
    build:
      context: ./router
    container_name: router
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./certbot/certs:/etc/nginx/certs:ro
      - ./certbot/certbot-www:/var/www/certbot:ro
    restart: unless-stopped
    networks: [net]

  static:
    image: nginx:alpine
    container_name: router
    expose:
      - "80"
    volumes:
      # - ./frontend/dist:/usr/share/nginx/html:ro                # билд фронта
      # - ./devops/static/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks: [net]

  
  certbot:
    build:
      context: ./certbot
    container_name: certbot
    environment:
      - DOMAIN=tandem.websales.app
      - EMAIL=mail@example.com
      - MODE=prod
    volumes:
      - ./certbot/certs:/etc/letsencrypt
      - ./certbot/certbot-www:/var/www/certbot
    networks: [net]
  

  frontend:
    image: nginx:alpine
    container_name: frontend
    command: sh -c "echo '<h1>Frontend stub</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    expose: ["80"]
    networks: [net]

  backend:
    image: nginx:alpine
    container_name: backend
    command: sh -c "echo '{\"status\":\"ok\"}' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    expose: ["8000"]
    networks: [net]

networks:
  net:
    driver: bridge

