version: "3.9"

services:
  router:
    build:
      context: ./router
    container_name: router
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./volumes/certs:/etc/nginx/certs:ro
      - ./volumes/certbot-www:/var/www/certbot:ro
    restart: unless-stopped
    networks: [net]

  

  frontend:
    image: nginx:alpine
    container_name: frontend
    command: sh -c "echo '<h1>Frontend stub</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    expose: ["80"]
    networks: [net]

  backend:
    image: nginx:alpine
    container_name: backend
    command: sh -c "echo '{\"status\":\"ok\"}' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    expose: ["8000"]
    networks: [net]

networks:
  net:
    driver: bridge

