version: "3.9"

services:
  edge:
    build:
      context: ./edge
    ports:
      - "80:80"
      - "443:443"
    # volumes:
      # - :/etc/nginx/certs:ro
      # - :/var/www/certbot:ro
    restart: unless-stopped
    networks: [net]

  cdn:
    build:
      context: ./cdn
    expose:
      - "80"
    networks: [net]

networks:
  net:
    driver: bridge

